name: streamlit
channels:
  - defaults
dependencies:
  - blas=1.0
  - bottleneck=1.4.2
  - bzip2=1.0.8
  - ca-certificates=2025.9.9
  - cairo=1.18.4
  - contourpy=1.3.1
  - cycler=0.11.0
  - expat=2.7.1
  - fontconfig=2.15.0
  - fonttools=4.60.1
  - freetype=2.13.3
  - graphite2=1.3.14
  - harfbuzz=10.2.0
  - icc_rt=2022.1.0
  - icu=73.1
  - intel-openmp=2025.0.0
  - jpeg=9f
  - kiwisolver=1.4.8
  - lcms2=2.16
  - lerc=3.0
  - libdeflate=1.17
  - libffi=3.4.4
  - libglib=2.84.4
  - libiconv=1.16
  - libkrb5=1.21.3
  - libpng=1.6.50
  - libpq=17.6
  - libtiff=4.5.1
  - libwebp-base=1.3.2
  - libxml2=2.13.9
  - libzlib=1.3.1
  - lz4-c=1.9.4
  - matplotlib=3.10.6
  - matplotlib-base=3.10.6
  - mkl=2025.0.0
  - mkl-service=2.5.2
  - mkl_fft=2.1.1
  - mkl_random=1.3.0
  - mysql-common=9.3.0
  - mysql-libs=9.3.0
  - numexpr=2.14.1
  - numpy=2.3.4
  - numpy-base=2.3.4
  - openjpeg=2.5.2
  - openssl=3.0.18
  - packaging=25.0
  - pandas=2.3.3
  - pcre2=10.46
  - pip=25.2
  - pixman=0.46.4
  - pyparsing=3.2.0
  - pyqt=6.9.1
  - pyqt6-sip=13.10.2
  - python=3.11.14
  - python-dateutil=2.9.0post0
  - python-tzdata=2025.2
  - pytz=2025.2
  - qtbase=6.9.2
  - qtdeclarative=6.9.2
  - qtsvg=6.9.2
  - qttools=6.9.2
  - qtwebchannel=6.9.2
  - qtwebsockets=6.9.2
  - scipy=1.16.2
  - setuptools=80.9.0
  - sip=6.12.0
  - six=1.17.0
  - sqlite=3.50.2
  - tbb=2022.0.0
  - tbb-devel=2022.0.0
  - tk=8.6.15
  - tzdata=2025b
  - ucrt=10.0.22621.0
  - vc=14.3
  - vc14_runtime=14.44.35208
  - vs2015_runtime=14.44.35208
  - wheel=0.45.1
  - xz=5.6.4
  - zlib=1.3.1
  - zstd=1.5.7
  - pip:
      - altair==5.5.0
      - annotated-types==0.7.0
      - anyio==4.11.0
      - attrs==25.4.0
      - blinker==1.9.0
      - cachetools==6.2.1
      - certifi==2025.10.5
      - charset-normalizer==3.4.4
      - click==8.3.0
      - colorama==0.4.6
      - distro==1.9.0
      - gitdb==4.0.12
      - gitpython==3.1.45
      - h11==0.16.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - idna==3.11
      - jinja2==3.1.6
      - jiter==0.11.1
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - markupsafe==3.0.3
      - narwhals==2.10.1
      - openai==2.6.1
      - pillow==12.0.0
      - protobuf==6.33.0
      - pyarrow==21.0.0
      - pydantic==2.12.3
      - pydantic-core==2.41.4
      - pydeck==0.9.1
      - python-dotenv==1.2.1
      - referencing==0.37.0
      - regex==2025.10.23
      - requests==2.32.5
      - rpds-py==0.28.0
      - smmap==5.0.2
      - sniffio==1.3.1
      - streamlit==1.51.0
      - tenacity==9.1.2
      - tiktoken==0.12.0
      - toml==0.10.2
      - tornado==6.5.2
      - tqdm==4.67.1
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - urllib3==2.5.0
      - watchdog==6.0.0
prefix: C:\Users\leed39\AppData\Local\anaconda3\envs\streamlit
